settings:
  legacy:
    force: false
    interval: 50ms
server:
  status: false
  open: false
  port: 5002
  host: localhost
schema:
- name: eco-report
  path: .
  commands:
    run:
      status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    - toml
    ignored_paths:
    - .git
    - .realize
    - vendor
